// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLSV.Data;

#nullable disable

namespace QLSV.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231221063540_Create_table_SinhVien")]
    partial class Create_table_SinhVien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("QLSV.Models.Diem", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiemMH")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenMH")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSV")
                        .HasColumnType("TEXT");

                    b.HasKey("MaSV");

                    b.ToTable("Diem");
                });

            modelBuilder.Entity("QLSV.Models.Khoa", b =>
                {
                    b.Property<string>("Makhoa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenkhoa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Makhoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("QLSV.Models.Lop", b =>
                {
                    b.Property<string>("Malop")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenlop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Malop");

                    b.ToTable("Lop");
                });

            modelBuilder.Entity("QLSV.Models.Quanlydiem", b =>
                {
                    b.Property<int>("Sothutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Diem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenmonhoc")
                        .HasColumnType("TEXT");

                    b.HasKey("Sothutu");

                    b.ToTable("Quanlydiem");
                });

            modelBuilder.Entity("QLSV.Models.Quanlymonhoc", b =>
                {
                    b.Property<string>("Mamonhoc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenmonhoc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Mamonhoc");

                    b.ToTable("Quanlymonhoc");
                });

            modelBuilder.Entity("QLSV.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hovaten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Makhoa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Malop")
                        .HasColumnType("TEXT");

                    b.HasKey("MaSV");

                    b.HasIndex("Makhoa");

                    b.HasIndex("Malop");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("QLSV.Models.SinhVien", b =>
                {
                    b.HasOne("QLSV.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("Makhoa");

                    b.HasOne("QLSV.Models.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("Malop");

                    b.Navigation("Khoa");

                    b.Navigation("Lop");
                });
#pragma warning restore 612, 618
        }
    }
}
